name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform running on main branch (fmt, init, validate, plan, apply)
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: eu-west-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="region=eu-west-1"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply (only on main)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
      
      - name: Get Ansible public IP
        id: get_ip
        run: |
          echo "ANSIBLE_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
  
      - name: Copy private key to Ansible instance
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Copying SSH key to $ANSIBLE_IP"
          scp -i ubuntu_KP.pem -o StrictHostKeyChecking=no ./ubuntu_KP.pem ubuntu@$ANSIBLE_IP:/home/ubuntu/ansible/
          ssh -i ubuntu_KP.pem -o StrictHostKeyChecking=no ubuntu@$ANSIBLE_IP "chmod 600 /home/ubuntu/ansible/ubuntu_KP.pem && chown ubuntu:ubuntu /home/ubuntu/ansible/ubuntu_KP.pem"
  